### ISSUE TITLE
Support Webpack 3.5.X

### ISSUE THREAD

**Issue by arnaudmorisset** [NoRedInk/elm-assets-loader#10]
Hello,

I'm currently trying to install your package but I encounter the following problem:

`elm-assets-loader@0.3.0 requires a peer of webpack@>=1.13.3 <3.0.0 but none was installed.`

However, my project use Webpack 3.5.6 and I can't rollback to a previous version.

Please, can you add the support of the newer version of Webpack?

**Comment by Janiczek** [comment]
Aaaand webpack 4 :)

**Comment by evolve2k** [comment]
bump.

**Comment by evolve2k** [comment]
It looks like @alviv have addressed this, could you look at merging in their changes to the project which pretty much just update the supported version of weback.

ref: https://github.com/alvivi/elm-assets-loader

**Comment by michaelglass** [comment]
released 0.4.0
