### ISSUE TITLE
Peer dependencies don't include webpack 4.x.x

### ISSUE THREAD

**Issue by Lattyware** [NoRedInk/elm-assets-loader#15]
The intent is clearly to support this version (4.6.0 is tested), but the peer dependencies currently list:

`"webpack": ">=1.13.3 <4.0.0"`

I assume this is a mistake, and it should be `< 5.0.0` to support 4.x.x

**Comment by muelli** [comment]
right. `yarn check` is giving an error about this which is a bit annoying:

```
error "elm-assets-loader#webpack@>=1.13.3 <4.0.0" doesn't satisfy found match of "webpack@4.21.0"
```

**Comment by michaelglass** [comment]
fixed on master
