### ISSUE TITLE
Cannot find module 'babel-core'

### ISSUE THREAD

**Issue by jligeza** [NoRedInk/elm-assets-loader#9]
Webpack 2 fails building the package fs the `elm-assets-loader` is added to the config.

```
...
  module: {
    rules: [{
        test: /\.elm$/,
        exclude: [/elm-stuff/, /node_modules/],
        use: [{
          loader: 'elm-webpack-loader',
          options: { verbose: true, warn: true }
        }, {
          loader: 'elm-assets-loader',
          options: { module: 'Assets', tagger: 'AssetPath' }
        }]
      }, {
        test: /\.(jpe?g|png|gif|svg)$/i,
        use: {
          loader: 'file-loader',
          options: {name: '[name]-[hash].[ext]'}
        }
      }
    ]
  },
...
```
If I install the missing lib, then it tries to read the `Main.elm` file with babel, throwing parsing error at the very first line of code (main module declaration), what puzzles me.

What might be causing the issue and how do I fix it?

**Comment by ento** [comment]
One thing I see is the order of the loaders: [loaders are applied from last to first configured](https://webpack.js.org/configuration/module/#rule-use), so try:

```
        use: [{
          loader: 'elm-assets-loader',
          options: { module: 'Assets', tagger: 'AssetPath' }
        }, {
          loader: 'elm-webpack-loader',
          options: { verbose: true, warn: true }
        }]
```

**Comment by jligeza** [comment]
I have fixed the issue by changing 19th line from `loaderUtils.getLoaderConfig` to `loaderUtils.getOptions` (the former was replaced in the lib) and resolving all additional dependencies that webpack asked for while compiling (babel-core, file-loader).
...
Also, the loader order was incorrect, as the assets should be first.

**Comment by ento** [comment]
v0.3.0 has been published with the change to use `loaderUtils.getOptions`. Would be great if you can try it out - closing this issue for now, assuming 0.3.0 will fix it.

babel-core is marked as a peer dependency of this package - you should be able to spot missing dependencies in the output of npm install:

![image](https://user-images.githubusercontent.com/21108/27087438-e8dbe586-5009-11e7-82b6-cc0e690d523b.png)

As for file-loader: this package itself doesn't depend on file-loader, so I haven't marked it as a dependency.

**Comment by jligeza** [comment]
I can confirm it works now.

**Comment by ento** [comment]
Thanks for confirming!
